# Generated by Django 3.2.8 on 2022-07-01 17:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='imdb',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='img',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('img', models.CharField(max_length=250)),
                ('imdb', models.CharField(max_length=250)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.playlist')),
            ],
        ),
    ]
